### PR TITLE
[1.22] docs: launch fixxref with the detected version of python

### PR DESCRIPTION
**Pull request by sc0w**
Fixes the build in debian

### CODE REVIEW

**Comment by monsta** [comment]
Maybe it's better to launch `fixxref.py` with the detected version of Python?

```diff
--- a/docs/Makefile.am
+++ b/docs/Makefile.am
@@ -94,7 +94,7 @@ $(HTML_FILES): $(REFERENCE_DEPS)
                 --stringparam gtkdoc.bookname "caja-python" \
                 --stringparam gtkdoc.version ${REF_VERSION} \
                 $(HTML_STYLE) $(srcdir)/reference/caja-python-ref.xml
-       $(FIXXREF) -i xsl $(BUILDDIR)/html
+       $(PYTHON) $(FIXXREF) -i xsl $(BUILDDIR)/html
        touch $@
 
 endif
```

**Comment by sc0w** [comment]
@monsta done, it works, thanks

we must do the same to 1.24 and master?

**Comment by monsta** [comment]
The docs aren't built in Travis with this change (again), but I've tested it locally with and without `PYTHON=python3` environment variable, and with `--enable-gtk-doc`. All good. We won't need this in master or 1.24, as there's always Python 3.

**Comment by sc0w** [comment]
I noticed your commit in other branch and I cherry-picked here, you are the author

**Comment by monsta** [comment]
Ah yes, it was my test branch. I guess we can merge this PR?

**Pull request merged**
