### PR TITLE
Initialize Travis CI support

### PR DESCRIPTION
**Pull request by yetist**
After merge #41 , build will pass.

### CODE REVIEW

**Comment by raveit65** [comment]
Is it possible to add `export PYTHON=python3` before configure started to the build, to avoid droping python2 support?
See what i did for fedora https://src.fedoraproject.org/cgit/rpms/python-caja.git/tree/python-caja.spec#n84

**Comment by yetist** [comment]
OK, I will try it.

**Comment by raveit65** [comment]
Looks like the the fix from other PR is needed for archlinux build.

**Comment by yetist** [comment]
Yes, because python on archlinux is python3, not python2, and https://github.com/mate-desktop/python-caja/blob/master/docs/xsl/fixxref.py#L1 use python, not python2 or python3.

**Comment by raveit65** [comment]
I would simply cherry-pick the commit to this PR here, than we see that everything is working.

**Pull request merged**
