### PR TITLE
Travis 1.20

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by raveit65** [comment]
Distcheck failed with docs.
https://travis-ci.org/mate-desktop/python-caja/jobs/503973194
```
make[3]: Leaving directory '/rootdir/po'
 (cd docs && make  top_distdir=../python-caja-1.20.2 distdir=../python-caja-1.20.2/docs \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory '/rootdir/docs'
make[3]: *** No rule to make target 'reference/builddate.xml', needed by 'distdir'.  Stop.
make[3]: Leaving directory '/rootdir/docs'
make[2]: *** [Makefile:659: distdir-am] Error 1
make[2]: Leaving directory '/rootdir'
make[1]: *** [Makefile:652: distdir] Error 2
make[1]: Leaving directory '/rootdir'
make: *** [Makefile:759: dist] Error 2
!!! ERROR: run command [docker exec -t python-caja-fedora-build /rootdir/after_scripts].
The command "./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools" exited with 1.
```
Here i need help.
Not sure if we ever do a commit in 1.20 branch.
Maybe we can ignore this?

**Comment by raveit65** [comment]
Now only build for archlinux failed.
https://travis-ci.org/mate-desktop/python-caja/jobs/504005247
```
Writing index.sgml for book(caja-python-reference)
./xsl/fixxref.py -i xsl ../docs/html
Writing caja-python.devhelp for book(caja-python-reference)
  File "./xsl/fixxref.py", line 52
    except getopt.error, e:
                       ^
SyntaxError: invalid syntax
make[2]: *** [Makefile:664: html/index.html] Error 1
```

**Comment by raveit65** [comment]
Maybe someone have an idea to fix building gtk-docs for ArchLinux?

**Comment by raveit65** [comment]
Was python-caja ever build for ArchLinux?

**Comment by yetist** [comment]
the error seems ptyhon3 error, on archlinux default python is python3, maybe you should use PYTHON=python2?

**Comment by raveit65** [comment]
I use `PYTHON=python2`
And i tried `python2-gobject` or `pygobject-devel` as build requires already.

**Comment by yetist** [comment]
I saw you definded PYTHON alteady, so we need write a patch for archlinux, the minimal change is to modify docs/Makefile.am at line 6, use python2 to run the py script.

**Comment by yetist** [comment]
Or you assign me the archlinux compilation problem, I will go back and deal with it.

**Comment by raveit65** [comment]
Cool, thanks

**Comment by yetist** [comment]
@raveit65 

#44 can fix the build error on archlinux, I use the `temp-test` branch for test, travis log is here: 
https://travis-ci.org/mate-desktop/python-caja/builds/504198467

**Comment by raveit65** [comment]
All travis builds are fine now.

**Pull request merged**
