### PR TITLE
Python 3.13 removes PySys_SetArgv(): set sys.argv in Python language.

### PR DESCRIPTION
**Pull request by monnerat**
Thanks for considering it!

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
LGTM,
python-caja builds fine for all archs in fedora rawhide with python-3.13.
https://koji.fedoraproject.org/koji/buildinfo?buildID=2315785

**Comment by monnerat** [comment]
> python-caja builds fine for all archs in fedora rawhide with python-3.13.

Rawhide still has Python 3.12. I however performed a local x86_64 mock build with Python 3.13 successfully.

**Comment by raveit65** [comment]
Ahh, i misread rhbz report. Python-3.13 is for fedora 41. Rawhide is currently fedora 40.
from https://bugzilla.redhat.com/show_bug.cgi?id=2247264#c0
`Python 3.13 is planned to be included in Fedora 41.`
But fixed version `1:1.26.0-8` builds fine at python-3.13 test at fedora copr repository https://copr.fedorainfracloud.org/coprs/g/python/python3.13/package/python-caja/

**Comment by lukefromdc** [comment]
In Debian Unstable I have python 3.11 installed. Python 3.12 is available but nothing depends on it yet as of last update

**Review by lukefromdc — APPROVED** [review]
With python 3.11 this does not cause any problems, a test build went fine and my one python extension (open as administrator) works fine with this installed after restarting caja

**Comment by lukefromdc** [comment]
Asking if anyone else wants to review this, just in case

**Comment by monnerat** [comment]
Thanks for merge.

**Comment by lukefromdc** [comment]
Thanks for submitting this PR: python 3.13 may be a bit down the road for many distros but all (or almost all) will eventually use 3.13 or later by default.

**Pull request merged**
