### PR TITLE
Make Caja.OperationHandle usable.

### PR DESCRIPTION
**Pull request by monnerat**
The Caja.OperationHandle.handle property is added: this gives access to the
effective handle taking the form of a non-zero signed integer that can be
stored in a void pointer. Trying to set this property with an invalid value
raises an exception.
Upon update_file_info_full call, the new Caja.OperationHandle is preset with
a "unique" non-null value generated from an atomic counter. When the python
method returns, the handle value is transmitted to Caja whatever it is:
this fixes the problem of Caja expecting a non-null handle when
CAJA_OPERATION_IN_PROGRESS is returned.

Tests of this commit performed with 64-bit Python 2 and 3 were successful.

Ref: https://github.com/mate-desktop/python-caja/issues/36

### CODE REVIEW

**Comment by raveit65** [comment]
We are in feature freeze for 1.22 release.
I think this belongs in 1.23 development.

**Comment by raveit65** [comment]
@monnerat 
Can you please rebase against master?
This should enable travis-CI for this PR.

**Comment by monnerat** [comment]
> Can you please rebase against master?

Done. Travis CI successful.

**Comment by monnerat** [comment]
Thanks for merging :-)

**Comment by raveit65** [comment]
@monnerat 
See https://bugzilla.redhat.com/show_bug.cgi?id=1718331
Next round of python upgrade. :/

**Comment by monnerat** [comment]
> Next round of python upgrade. :/

@raveit65: see PR https://github.com/mate-desktop/python-caja/pull/46

**Pull request merged**
