### PR TITLE
Travis CI: enable clang analyzer and cppcheck html reports

### PR DESCRIPTION
**Pull request by sc0w**
`scan-build: 1 bug found.`

@raveit65 @yetist 

I need some help, https://python-caja.mate-desktop.dev isn't working

### CODE REVIEW

**Comment by yetist** [comment]
The dns of python-caja.mate-desktop.dev is ok.
```
$ dig python-caja.mate-desktop.dev|grep CNAME
python-caja.mate-desktop.dev. 3464 IN	CNAME	mate-desktop.github.io.
```

**Comment by raveit65** [comment]
Let's wait a while, `https` isn't enabled and checkbox is grey out..
Screenshot at 2020-01-12 11-41-58
Simple `http` works fine.
Screenshot at 2020-01-12 11-44-33

**Comment by sc0w** [comment]
thanks, now https://python-caja.mate-desktop.dev is working 👍

**Comment by raveit65** [comment]
cppcheck result looks weird or is this my browser (firefox, chrome)?
Screenshot at 2020-01-13 17-35-19

**Comment by sc0w** [comment]
@raveit65 

I think it is an issue in the httml report, I mean, the tool which makes the website, probably because there is no issues detected by cppcheck and the report is very little.

btw, the look is ok in firefox and 300% zoom

**Pull request merged**
