### PR TITLE
Report effective Python version and library location at the end of configure.

### PR DESCRIPTION
**Pull request by monnerat**
This replaces PR #37

### CODE REVIEW

**Comment by lukefromdc** [comment]
This is reporting the python version at configuration, but on my Debian setup always reports python 2.7 as the version to be built against, can't set up a python 3 build with  --with-python=/usr/bin/python3.7 or with --with-python3

**Comment by monnerat** [comment]
As stated in PR #37 discussion, this option has been dropped since the standard way of doing is

`./autogen.sh PYTHON=/usr/bin/python3`
or
`PYTHON=/usr/bin/python3 ./autogen.sh`

You can see it described when you submit

`./autogen.sh --help`

**Comment by lukefromdc** [comment]
OK, that worked and I used the same Debian patch as before for a python 3 build, the caja-admin branch for Python 3 did not work, giving this error:
```
(caja:6979): Caja-Python-WARNING **: 22:16:57.043: caja_python_init_python failed
ImportError: could not import gobject (error was: ImportError('/usr/lib/python3/dist-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError'))
```

**Comment by monnerat** [comment]
I've never seen it before and caja-admin works very well on Fedora.
Maybe you have not installed gobject for Python3 ?
Else I suspect it's again some distribution-specific problem, maybe not in python-caja itself.
If you tell me your precise OS version, I can create a VM here for tests and debug purpose.

**Comment by lukefromdc** [comment]
My Debian unstable version is too heavily modified to duplicate without sending a file image. Don't worry about it, I don't normally use caja-admin and was just trying to help but this is more than I can handle. I know very little about python and do no programming in it, just didn't pick a good test application for python-caja itself. I am going to have to let this one go as I am out of time for it.

**Comment by monnerat** [comment]
OK I understand. Anyway I presume this error will occur for all Python extensions (you can try with the ones in the examples directory). Try only one a a time.
If I have time, I'll try on a debian unstable not "heavily modified".
Thanks for your help and testing.

**Comment by lukefromdc** [comment]
The normal caja-admin package works fine with a Python 2 build of this with the usual Debian patch, so looks like you didn't break anything in Python 2 at least.

**Comment by monsta** [comment]
@lukefromdc: which summary did you get at the end of configure?

I have the proper dirs in case of both Pythons:

```
 caja-python 1.21.1

      Caja Prefix:             /usr
      Python version:          2.7
      Python library location: /usr/lib/x86_64-linux-gnu
      Documentation:           yes
```
```
 caja-python 1.21.1

      Caja Prefix:             /usr
      Python version:          3.7
      Python library location: /usr/lib/x86_64-linux-gnu
      Documentation:           yes
```

**Comment by lukefromdc** [comment]
For python 3 I got

 caja-python 1.21.1

      Caja Prefix:             /usr
      Python version:          3.7
      Python library location: /usr/lib/x86_64-linux-gnu
      Documentation:           no

**Comment by monsta** [comment]
Ok, it looks good, so it's not the cause of caja-admin not working...

I've tried caja-admin ported by @monnerat and it worked for me. I had to use cmake as per build instructions from the repo:

```
mkdir build
cd build
cmake ..
```
After that I simply replaced `/usr/share/caja-python/extensions/caja-admin.py` with just generated `build/extension/caja-admin.py` and restarted Caja.

**Comment by monsta** [comment]
You can also try the `examples` dir from this repo. Just copy the Python files to `/usr/share/caja-python/extensions/` or `~/.local/share/caja-python/extensions/` and restart Caja.

**Comment by raveit65** [comment]
Thanks

**Comment by monnerat** [comment]
Thanks for merging :-)

**Pull request merged**
